### PR TITLE
CATTY-34: Project with Arduino Brick not starting

### PR DESCRIPTION
**Pull request by Bomml**
*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catty/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Verify that the Jira ticket is in the status *Ready for Development*
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s git workflow (rebase and squash your commits)
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#catty* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by Bortol15** [comment]
Hey @Bomml ! Projects with Arduino Brick start now, great! :) I tested it manually and do have one point, the view is showing up in the "new" iOS 13 page sheet style (see attachements) which seems not consistent with the non-arduino scene to me, do you think it should be changed or is it better in that way?
IMG_7666
IMG_E32CE2356D42-1

**Comment by Bomml** [comment]
Thank you. It was my fault. Forgot to test on iOS13. Now it shows a fullscreen;D

**Comment by Bortol15** [comment]
Jenkins, retest this please

**Comment by m-herold** [comment]
Thanks!

**Pull request merged**
