### PR TITLE
fixes ScreenRecording availability issue

### PR DESCRIPTION
**Pull request by rsamer**

### CODE REVIEW

**Comment by m-herold** [comment]
When starting the app on iPhone 4S and 5 the sidebar looks like on the following screenshot:

screen shot 2015-11-08 at 20 31 53

**Comment by rsamer** [comment]
do the buttons disappear when AirPlay is active?
Otherwise I cannot reproduce the problem.

**Comment by m-herold** [comment]
On my environment this behaviour is independent from AirPlay (just tested it). I have tested it on a iPhone 5 and 4S Simulator running iOS 9.1. Does the sidebar look normal when testing with your 4S/5 simulator?

**Comment by marcslavec** [comment]
The issue is located in ScenePresenterViewController line 283. 
button.hidden -> this is the setup function for *every* menu button -> if recording is not available every button in the menu is hidden

**Comment by rsamer** [comment]
Thx for the hint. I'll fix it in the evening.

**Comment by rsamer** [comment]
fixed. Please retest...

**Pull request merged**
