### PR TITLE
IOS-244 #done

### PR DESCRIPTION
**Pull request by marcslavec**

### CODE REVIEW

**Comment by m-herold** [comment]
@marcslavec Can we display this alert only when the current program is using at least one of the sensors handled in this function?

**Comment by marcslavec** [comment]
@m-herold I will look at this issue tomorrow!

**Comment by marcslavec** [comment]
@m-herold What should we do now? We can't do it while parsing the program. Meanwhile this is the best solution when checking it in the scene.

**Comment by rsamer** [comment]
I think we could add a uses-sensors property (containing all sensors involved) to the CBXMLParser class. After parsing the program it is up to the ViewController to either show an alert or not.

**Comment by m-herold** [comment]
I would also go for a mechanism where all sensors are getting registered (e.g. while parsing the program). A sensor could be registered by a [object registerSensor:] method (and then added to a local property for example). I am still not sure what 'object' should be - either the CBXMLParser or the Program itself? I think it would make sense to have it in the Program because it can be accessed anywhere but since it would be the easiest way to register a sensor while parsing the program I am not sure which class would make more sense. Any ideas?

**Comment by rsamer** [comment]
hm, it depends on your preference. I think both solutions have their pros and cons...

**Comment by marcslavec** [comment]
I think the easiest way would be to "register" sensors while parsing. This could also be easily adopted to the bluetooth sensors/bricks to check if the program needs bluetooth connection. With this future motive I would suggest the parser.

**Comment by m-herold** [comment]
Ok, I would prefer registering them in the parser as well. But where should this information be held? In the Program or the CBXMLParser itself (property-wise)?

**Comment by marcslavec** [comment]
For the sensors the shared sensor manager would be a possibility. Stored in the singleton object. Or as you mentioned the program.

**Comment by marcslavec** [comment]
This pull request should be closed! -> everything is implemented in the resource management

**Comment by m-herold** [comment]
Resource management has been merged with PR #685.

**Pull request closed without merging**
