### PR TITLE
IOS-119 #done

### PR DESCRIPTION
**Pull request by marcslavec**

### CODE REVIEW

**Comment by m-herold** [comment]
Please rename the title of the alert to "No Internet Connection" (currently: "Pocket Code"). This should be done according to HE No. 2 (line 15).

screen shot 2015-08-14 at 12 14 47

Also, when the internet connection breaks while being in the HelpWebViewController, the error message shown differs from the message above:

screen shot 2015-08-14 at 12 15 28

Please change error message to "No internet connection available" (like in first screenshot). Reproduce by switching to HelpWebViewController, turning off WiFi/internet connection and pressing on "Step by Step". 

When the internet connection breaks while being in the DownloadTabBarController ("Explore") no error message is shown (endless spinner instead). Please show error message in this controller as well.

screen shot 2015-08-14 at 12 16 39

**Comment by marcslavec** [comment]
The loading indicator does not stop immediately after the alert, but I really don't know why because I call the function directly after the alert. But it stops after some seconds

**Comment by m-herold** [comment]
The hideLoadingView method is called from a completionHandler which means we are not on the main thread. Since this is a UI call, try dispatching the call to the main queue.

**Comment by marcslavec** [comment]
Dispatching the call to the main queue does not help that much. It's a little bit faster but not as expected.

**Comment by rsamer** [comment]
AFAIK the UIKit framework suffers from not being thread-safe, i.e. if you perform UIKit operations on another queue/thread, you can never guarantee that this causes no app-crashes in the future.
Multiple UIKit operations (especially all UIKit classes that inherit from UIResponder) executed at the same time may lead (sometimes!) to unexpected states and behaviour in UIKit itself. The issue is that concurrent situations are hard to debug and those bugs are not really reproducible.
I think that's the reason why so many people (including Apple itself) warn you to only use the main-queue for those purposes.

**Pull request merged**
