### PR TITLE
Ble sensors

### PR DESCRIPTION
**Pull request by marcslavec**

### CODE REVIEW

**Comment by marcslavec** [comment]
This pull request solves the main queue blocking issue for Bluetooth sensors in Formulas

**Comment by rsamer** [comment]
I'll review this PR soon.

@marc: Please move your for-in-Loop (BufferedElements) down below the section where we are iterating through our HighPerformanceInstructions.
This is really crucial for us in order to maintain our (high) performance-level and to avoid negative influences on some interpreter-optimizations.

**Comment by marcslavec** [comment]
please wait till the other PR("Fixes") is merged, because unfortunately I branched from the Fixes branch of the other pull request instead of the master.

**Comment by rsamer** [comment]
ACK!

**Comment by marcslavec** [comment]
you can now merge this PR -> #done

**Pull request merged**
