### PR TITLE
CATTY-707 fix landscape mode

### PR DESCRIPTION
**Pull request by mariomauberger**
[CATTY-707](https://jira.catrob.at/browse/CATTY-707)

fixed MenuView (buttons now look good again)
fixed Axis arrows
fixed alignment in landscape mode

Screenshot 2023-05-05 at 09 23 04

Screenshot 2023-05-05 at 09 23 45

Screenshot 2023-05-05 at 09 24 10

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catty/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Verify that the Jira ticket is in the status *Ready for Development*
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s git workflow (rebase and squash your commits)
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#catty* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by wallisch** [comment]
Somehow on my physical device (iPhone 12, 16.4.1) the canvas is off center.
IMG_1840

Animation seems glitchy too.
https://user-images.githubusercontent.com/4726602/236425376-579930ca-b139-431a-a2a8-d268cbcdac14.MP4

**Comment by mariomauberger** [comment]
> Somehow on my physical device (iPhone 12, 16.4.1) the canvas is off center. IMG_1840
> 
> Animation seems glitchy too. https://user-images.githubusercontent.com/4726602/236425376-579930ca-b139-431a-a2a8-d268cbcdac14.MP4



Canvas center should be fixed. 

Glitchy animation, not sure yet how I can fix that but I will check.

**Comment by wallisch** [comment]
Animation is OK i guess, but somethings stilll not quite right:
- On first stage launch the axis are not displayed correctly
- On subsequent launch they are, but twice, and the menu is broken again

https://github.com/Catrobat/Catty/assets/4726602/99084e6e-3add-41c0-8d18-df96407dd3c8

**Comment by mariomauberger** [comment]
> Animation is OK i guess, but somethings stilll not quite right:
> 
> * On first stage launch the axis are not displayed correctly
> * On subsequent launch they are, but twice, and the menu is broken again
> 
>  video_2023-05-12_02-17-44.mp4

can you reproduce that? 
I tried it on multiple devices and could not reproduce.

But I fixed a bug with the values in the axis

**Comment by wallisch** [comment]
Looks good now, but 2 tests fail (rightfully i think), the axis values are somehow unscaled @1X  (422) instead of the actual resolution @3X (1266)

**Comment by mariomauberger** [comment]
> Looks good now, but 2 tests fail (rightfully i think), the axis values are somehow unscaled @1x (422) instead of the actual resolution @3x (1266)

should be fixed

**Comment by mariomauberger** [comment]
> > Looks good now, but 2 tests fail (rightfully i think), the axis values are somehow unscaled @1x (422) instead of the actual resolution @3x (1266)
> 
> should be fixed

changed back

**Review by wallisch — APPROVED** [review]

**Pull request merged**
