### PR TITLE
IOS-245 #done

### PR DESCRIPTION
**Pull request by marcslavec**

### CODE REVIEW

**Comment by rsamer** [comment]
I cannot find the record/stop button in the slide menu. (iOS9 + iPhone6)
Please only show this button if ReplayKit is available, i.e. the running OS is iOS9 *and* the device is an iPhone 5S or newer.

**Comment by m-herold** [comment]
Please do not display this icon if the device running the app is an iPhone 4S/5 since ReplayKit is not available on these devices.

**Comment by marcslavec** [comment]
i thought this is for all devices running iOS9. Therefore i just checked which version is running on the device.

**Comment by m-herold** [comment]
It's a little bit hard to find, but on the slides at http://devstreaming.apple.com/videos/wwdc/2015/6053hq2fz0ebo0lm/605/605_going_social_with_replaykit_and_game_center.pdf?dl=1 it states that ReplayKit is a feature for A7/A8 (and now A9) bases devices only (when running iOS 9).

**Comment by marcslavec** [comment]
Then the iPhone 5c is also not supported.

**Comment by rsamer** [comment]
Exactly, and none of the iPods.
Please do not perform any manual device and OS checks on your own in order to update the visibility state of the record button. This may lead to unexpected behaviour and app crashes since the availabilty state could change while the app is running, e.g. if the user activates air play screen sharing.

Best practise:
Implement the corresponding protocol of the screenRecordingDidChangeAvailability delegate method. This method informs you about availability changes.

After the scene setup is finished I'd recommend you to check the availability flag of the ScreenRecorder class object.

**Comment by rsamer** [comment]
To be discussed at the player presentation

**Pull request merged**
