### PR TITLE
IOS-152 #done

### PR DESCRIPTION
**Pull request by wallner90**
Changed „FunctionWithoutParametersAndBrackets“ to correct one using two
parameters.

### CODE REVIEW

**Comment by rsamer** [comment]
Catroid might to not officially support the POW operator at the moment.
There is an entry for that in the operators enum but I can't find any button in their FormulaEditor to see it in action. Please check if generated XMLs are compatible with Catroid...
Otherwise you could work around the problem by using the logarithmic law:
a^b == e^(b*ln(a))

**Comment by rsamer** [comment]
I've found out that it's still a known open issue for them: https://jira.catrob.at/browse/CAT-1066

**Comment by m-herold** [comment]
You are right, Ralph! I have created a new program with a WaitBrick having the POW operator as a formula. Thanks to Marco's changes this works perfectly in Catty:

screen shot 2015-08-25 at 12 27 01

But when I transfer this program to Catroid the POW operator is not interpreted correctly in the FE:

screen shot 2015-08-25 at 12 35 35

As mentioned by Ralph there is no such a button in their FE. So for compatibility reasons I would suggest to temporarily remove our "pow" button from the "Math" menu:

screen shot 2015-08-25 at 12 50 32

**Comment by rsamer** [comment]
+1

**Pull request merged**
