### PR TITLE
CATTY-159 Move plist files

### PR DESCRIPTION
**Pull request by DhrubojyotiBis1**
Moved the following files:
* App-Info.plist -> Supporting Files/App-Info.plist
* LoggerProperties.plist -> Supporting Files/Logger/LoggerProperties.plist
* Swell.plist -> Supporting Files/Logger/Swell.plist

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catty/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Verify that the Jira ticket is in the status *Ready for Development*
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s git workflow (rebase and squash your commits)
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#catty* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### CODE REVIEW

**Comment by DhrubojyotiBis1** [comment]
@m-herold  Please review and give feedback. Also, the build failed for similar reason.

**Comment by m-herold** [comment]
Jenkins, retest this please.

**Comment by DhrubojyotiBis1** [comment]
@m-herold build passing, please review. Do I need to squash this as well?

**Comment by DhrubojyotiBis1** [comment]
@GatCode do I need to change something?

**Comment by m-herold** [comment]
Jenkins, retest this please.

**Comment by m-herold** [comment]
Any news for this pull request? Suggestion: use grep to find invalid/not yet updated references:

```
grep -r "App-Info.plist" .
./src/fastlane/Fastfile:      plist_path: "Catty/App-Info.plist",
```

**Comment by DhrubojyotiBis1** [comment]
I will run the grep and test though it's running on my local machine. I will do this as soon as possible.

**Comment by m-herold** [comment]
Thanks and no worries, take your time.

**Comment by m-herold** [comment]
Jenkins, retest this please.

**Comment by m-herold** [comment]
Thanks for your changes! About to approve -- please squash your commits and let me know once this is done so I can merge this pr.

**Pull request merged**
