### PR TITLE
JENKINS-338 add unlock keychain to Jenkins pipelines

### PR DESCRIPTION
**Pull request by jampo**

### CODE REVIEW

**Comment by jampo** [comment]
Comment wait with merging until https://github.com/Catrobat/jenkins-pipeline-libraries/pull/10 is merged so the UnlockMACKeychain function is available

**Comment by m-herold** [comment]
Thank you! Can you please tell me once the other PR has been merged so I can test it?

**Comment by jampo** [comment]
Yes I will ping you again when its done - for now I retried the PR test Build with explicitly stating the shared library on my own branch which should alredy work see https://jenkins.catrob.at/job/Catty/job/PR-1182/2/ taking quite a while :(

**Comment by m-herold** [comment]
Yes, sorry for that, but from the console output it looks very good already!

**Pull request merged**
