### PR TITLE
IOS-160 #done

### PR DESCRIPTION
**Pull request by m-herold**
Changed "mutableCopy" to "copy" since NSNumber is immutable.

### CODE REVIEW

**Comment by rsamer** [comment]
In Catroid the OK button is automatically en-/disabled while typing for usability reasons, depending on whether the variable is already in use or not. It would be great to have this implemented.

**Comment by m-herold** [comment]
Just to get sure, are you talking about the feature shown at the screenshot?

screen shot 2015-09-01 at 09 57 10

**Comment by rsamer** [comment]
Yes, that is exactly what I've meant.

**Comment by m-herold** [comment]
Ok, I'll create a new issue on Jira for this feature.

**Pull request merged**
